services:
  - docker

matrix:
  include:
      language: python
      python: "3.7.3"
      before_install: cd dp3t_server
      install:
        - make setup
      
      script:
        - make test
        