services:
  - docker

matrix:
  include:
      language: python
      python: "3.7.3"
      before_install: cd dp3t_server
      install:
        - make setup
      
      script:
        - make test

  include:
    language: swift
    xcode_project: iosApp/dp3t.xcodeproj # path to your xcodeproj folder
    xcode_scheme: dp3t
    xcode_destination: platform=iOS Simulator,name=iPhone X,OS=11.4
  
