version: "3"

services:
  dp3t_server:
    build:
      context: ./dp3t_server
      dockerfile: local.Dockerfile
    image: jmather/dp3t_server:1.2
    container_name: dp3t_server
    command: bash -c "bash prestart.sh && python main.py"
    volumes:
     - ./dp3t_server:/app
    ports:
      - "5000:5000"
    depends_on:
      - "redis"

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
