version: "3"

services:
  dp3t_server:
    build: ./dp3t_server
    container_name: dp3t_server
    command: python main.py
    volumes:
     - ./dp3t_server:/app
    ports:
      - "5000:80"
    depends_on:
      - "redis"

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
